In [11]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2
from tqdm import tqdm
IMG_SIZE=120
import random
from random import shuffle
##all the directories in which all the data was given
TRAIN_DIR=["/home/dell/Desktop/Malignant_Images/","/home/dell/Desktop/Non_Malignant_a/","/home/dell/Desktop/Non_Malignant_b/","/home/dell/Desktop/Non_Malignant_c/"]
#here we have labeled the images if malignant then it returns 1 else it returns 0
def label_img(img):
    word_label=img.split('/')[4]

    if word_label=='Malignant_Images':return 1
    elif word_label=='Non_Malignant_a'or word_label=='Non_Malignant_b'or word_label=='Non_Malignant_c':return 0
#data is stored in seperate list for training it
def create_train_data():

    train_data=[]

    for train in TRAIN_DIR:
        for img in tqdm(cv2.os.listdir(train)):
            img_array = cv2.imread(os.path.join(train,img) ,cv2.IMREAD_GRAYSCALE)  # convert to array
            new_array = cv2.resize(img_array, (IMG_SIZE, IMG_SIZE))
            #for a particular image a label is given malignant or not
            label=label_img(train)
            # resize to normalize data size
            train_data.append([new_array, np.array(label)])
            
            
            """"label=label_img(train)
            path= cv2.os.path.join(train,img)
            img=cv2.resize(cv2.imread(path,cv2.IMREAD_GRAYSCALE),(IMG_SIZE,IMG_SIZE))
            train_data.append([np.array(img),np.array(label)])"""
     #here we shuffled the data        
    shuffle(train_data)
    np.save('training_data.npy',train_data)
    return train_data
train_data=create_train_data()

100%|██████████| 896/896 [03:34<00:00,  5.42it/s]


In [13]:
#two lists are then defined for putiiing features and labels
X = []
y = []

In [14]:
for features,label in train_data:
    X.append(features)
    y.append(label)

print(X[0].reshape(-1, IMG_SIZE, IMG_SIZE, 1))
#we cannot pass a list to a keras model so we have to convert it to a numpy array
X = np.array(X).reshape(-1, IMG_SIZE, IMG_SIZE, 1)


[[[[121]
   [163]
   [164]
   ...
   [165]
   [173]
   [163]]

  [[164]
   [169]
   [167]
   ...
   [172]
   [173]
   [162]]

  [[157]
   [165]
   [168]
   ...
   [162]
   [181]
   [163]]

  ...

  [[167]
   [167]
   [162]
   ...
   [148]
   [145]
   [165]]

  [[165]
   [155]
   [171]
   ...
   [150]
   [148]
   [150]]

  [[  0]
   [173]
   [170]
   ...
   [149]
   [155]
   [145]]]]


In [15]:
import pickle
#here using pickle library we have saved the data

pickle_out = open("x1.pickle","wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y1.pickle","wb")
pickle.dump(y, pickle_out)
pickle_out.close()



In [16]:


pickle_in = open("x1.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y1.pickle","rb")
y = pickle.load(pickle_in)



In [17]:
X[1]

array([[[  8],
        [  9],
        [  6],
        ...,
        [ 91],
        [ 62],
        [ 30]],

       [[  9],
        [ 12],
        [  4],
        ...,
        [107],
        [ 81],
        [ 46]],

       [[  9],
        [ 10],
        [ 11],
        ...,
        [132],
        [ 96],
        [ 74]],

       ...,

       [[ 89],
        [118],
        [133],
        ...,
        [214],
        [204],
        [193]],

       [[ 77],
        [105],
        [127],
        ...,
        [208],
        [197],
        [181]],

       [[ 58],
        [ 91],
        [115],
        ...,
        [208],
        [196],
        [174]]], dtype=uint8)

In [18]:
X

array([[[[121],
         [163],
         [164],
         ...,
         [165],
         [173],
         [163]],

        [[164],
         [169],
         [167],
         ...,
         [172],
         [173],
         [162]],

        [[157],
         [165],
         [168],
         ...,
         [162],
         [181],
         [163]],

        ...,

        [[167],
         [167],
         [162],
         ...,
         [148],
         [145],
         [165]],

        [[165],
         [155],
         [171],
         ...,
         [150],
         [148],
         [150]],

        [[  0],
         [173],
         [170],
         ...,
         [149],
         [155],
         [145]]],


       [[[  8],
         [  9],
         [  6],
         ...,
         [ 91],
         [ 62],
         [ 30]],

        [[  9],
         [ 12],
         [  4],
         ...,
         [107],
         [ 81],
         [ 46]],

        [[  9],
         [ 10],
         [ 11],
         ...,
         [132],
         [